import { Montserrat } from 'next/font/google';
import './globals.css';

import Header from '../components/Header';
import BottomNav from '../components/BottomNav';
import DisableInspect from '../components/DisableInspect'; 

const montserrat = Montserrat({
  variable: '--font-montserrat',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
});

export const metadata = {
  title: 'Mirror',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={montserrat.variable}>
      <body className="pt-[70px] font-montserrat bg-white text-black">
        <DisableInspect />
        <Header cartCount={3} />
        <main className="font-sans">{children}</main>
      </body>
    </html>
  );
}
